[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer_runs = 200
#viaIR = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.default.optimizer_details]
yul = true

# Formatter settings
[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = "short"
multiline_func_header = "all"
quote_style = "double"
number_underscore = "thousands"
wrap_comments = true
